function hst_loop(tempMatFile, dtSlice)
    
% usage ex:    
% hst_loop('Titp_T1C_p2std_1secAve.mat', .5/24);
%
% Inputs are:
% 'tempMatFile' : File generated by hst_hst2bin.m    
% 'dtSlice' : TimeStep in days (.5/24 is 30 min.)   
    
load(tempMatFile)    
nSlice = round((timeVec(end)-timeVec(1))/dtSlice)*2;
dt = timeVec(2) - timeVec(1);
lengthSlice = round(dtSlice/dt);
V = [0:.5:15];
V = [4:.2:15];
ZLIM = [0 6];
CLIM = [4 8];
CLIM = [6 9.5];

for i = 120:nSlice
    time0 = 1+(i-1)*lengthSlice/2;
    I = time0:time0+lengthSlice-1;
    windowTime = timeVec(I);
    windowT = Tbin(:,I);
    
% $$$     if i == 10
% $$$         save windowT.mat windowT
% $$$     end
    
    % *********************** Adjust_space.m ************************ %
    % Fields required by the function adjust_space.m. Please fill every
    % of the following and call "adjust_space" in the script whenever
    % you want. Do not touch four last fields
    ncol = 1; % no. subplot column
    nrow = 1; % no. subplot row
    dx = 0.03 ; % horiz. space between subplots
    dy = 0.04; % vert. space between subplots
    lefs = 0.12; % very left of figure
    rigs = 0.05; % very right of figure
    tops = 0.03; % top of figure
    bots = 0.1; % bottom of figure
    figw = (1-(lefs+rigs+(ncol-1)*dx))/ncol;
    figh = (1-(tops+bots+(nrow-1)*dy))/nrow;
    count_col = 1;
    count_row = 1;
    % *************************************************************** %
    figure('visible', 'off')
    %figure(3)
    clf
    set(gcf, 'PaperUnits', 'Centimeters', 'PaperPosition', [6 1 20 12])

% $$$     if i == 10
% $$$         %keyboard
% $$$     end
    contourf(windowTime, flipud(zVec), windowT, 100, 'linestyle', 'none')
    hold on
    contour(windowTime, flipud(zVec), windowT, V, 'color', 'k')
    hold off

    ylabel('mab (m)')
    %caxis([1032 1032.1]-1000)
    datetick
    %set(gca, 'xticklabel', []);
    %set(gca, 'yticklabel', []);
    set(gca, 'ydir', 'normal');
    set(gca, 'tickdir', 'out')
    xlim([min(windowTime) max(windowTime)])
    ylim([ZLIM])
    xlabel(sprintf(datestr(windowTime(1), 1)));
    adjust_space
    colorbar
    if exist('CLIM')
        caxis(CLIM)
    end
    
    
    outfile = sprintf('Deepwindow%06d.png',i);
    disp([outfile sprintf(' -  %d / %d', i, nSlice)])
    print('-dpng', '-r200', outfile)
    close all
    
    
end
